# Generated by Django 5.2.1 on 2025-05-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subdomain', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Discoverd Subdomain',
                'verbose_name_plural': 'Discovered Subdomains',
            },
        ),
        migrations.CreateModel(
            name='AssetWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField()),
                ('notify', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('fail', 'Faild'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Watcher',
                'verbose_name_plural': 'Asset Watchers',
            },
        ),
        migrations.CreateModel(
            name='JSFileWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('fail', 'Faild'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('notify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSFileWatcher',
                'verbose_name_plural': 'JSFileWatchers',
            },
        ),
        migrations.CreateModel(
            name='JSFileWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('jsfilewatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.jsfilewatcher')),
            ],
            options={
                'verbose_name': 'JSFileWatchList',
                'verbose_name_plural': 'JSFileWatchLists',
            },
        ),
        migrations.CreateModel(
            name='SubdomainHttpx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status_code', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('server', models.CharField(blank=True, max_length=150, null=True)),
                ('technologies', models.JSONField(default=list)),
                ('has_ssl', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
                ('port', models.IntegerField()),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx',
                'verbose_name_plural': 'Subdomain Httpxes',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(choices=[('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce')], default='subfinder', max_length=120)),
                ('asset_watcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='private_watchers.assetwatcher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='tool',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='private_watchers.tool'),
        ),
        migrations.CreateModel(
            name='WatchedJSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_url', models.URLField(max_length=150)),
                ('current_hash', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked', models.DateTimeField()),
                ('has_changed', models.BooleanField(default=False)),
                ('jsfilewatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.jsfilewatchlist')),
            ],
            options={
                'verbose_name': 'WatchedJSFile',
                'verbose_name_plural': 'WatchedJSFiles',
            },
        ),
        migrations.CreateModel(
            name='WatchedJSFileChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_hash', models.CharField(max_length=150, null=True)),
                ('new_hash', models.CharField(max_length=150, null=True)),
                ('diff_snipped', models.CharField(max_length=150, null=True)),
                ('changed_at', models.DateTimeField()),
                ('watchedjsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.watchedjsfile')),
            ],
            options={
                'verbose_name': 'WatchedJSFileChanged',
                'verbose_name_plural': 'WatchedJSFileChangeds',
            },
        ),
        migrations.CreateModel(
            name='WatchedWildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wildcard', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked', models.DateTimeField()),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.assetwatcher')),
            ],
            options={
                'verbose_name': 'Watched Wildcard',
                'verbose_name_plural': 'Watcher Wildcards',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.watchedwildcard'),
        ),
    ]
