# Generated by Django 5.2.1 on 2025-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedwildcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('fail', 'Faild'), ('cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
    ]
