# Generated by Django 5.2.1 on 2025-05-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0002_watchedwildcard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='user',
        ),
    ]
