# Generated by Django 5.2.1 on 2025-05-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0003_remove_tool_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='asset_watcher',
        ),
        migrations.AddField(
            model_name='watchedwildcard',
            name='tools',
            field=models.ManyToManyField(to='private_watchers.tool'),
        ),
    ]
