# Generated by Django 5.2.1 on 2025-05-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0004_remove_tool_asset_watcher_watchedwildcard_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedwildcard',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcards', to='private_watchers.assetwatcher'),
        ),
    ]
