# Generated by Django 5.2.1 on 2025-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0005_alter_watchedwildcard_watcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwatcher',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsfilewatcher',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchedjsfile',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchedjsfilechanged',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchedwildcard',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
