# Generated by Django 5.2.1 on 2025-05-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0006_alter_assetwatcher_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoversubdomain',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain', to='private_watchers.watchedwildcard'),
        ),
    ]
