# Generated by Django 5.2.1 on 2025-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0007_alter_discoversubdomain_wildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoversubdomain',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='NEW'),
        ),
    ]
