# Generated by Django 5.2.1 on 2025-05-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0008_discoversubdomain_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoversubdomain',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new'),
        ),
    ]
