# Generated by Django 5.2.1 on 2025-05-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0009_alter_discoversubdomain_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoversubdomain',
            options={'verbose_name': 'Discovered Subdomain', 'verbose_name_plural': 'Discovered Subdomains'},
        ),
        migrations.AlterField(
            model_name='discoversubdomain',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='discoversubdomain',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='private_watchers.tool'),
        ),
    ]
