# Generated by Django 5.2.1 on 2025-05-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0010_alter_discoversubdomain_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetwatcher',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='watchedwildcard',
            name='last_checked',
        ),
    ]
