# Generated by Django 5.2.1 on 2025-05-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0011_remove_assetwatcher_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwatcher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='jsfilewatcher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='watchedwildcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
    ]
