# Generated by Django 5.2.1 on 2025-05-12 10:38

import private_watchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0012_alter_assetwatcher_status_alter_jsfilewatcher_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetwatcher',
            name='wordlist',
            field=models.FileField(blank=True, default=private_watchers.models.default_wordlist_path, null=True, upload_to='private_watchers/wordlists/', validators=[private_watchers.models.validate_wordlist_file]),
        ),
    ]
