# Generated by Django 5.2.1 on 2025-05-12 10:52

import private_watchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0013_assetwatcher_wordlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwatcher',
            name='wordlist',
            field=models.FileField(blank=True, null=True, upload_to=private_watchers.models.user_wordlist_upload_path, validators=[private_watchers.models.validate_wordlist_file]),
        ),
    ]
