# Generated by Django 5.2.1 on 2025-05-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0014_alter_assetwatcher_wordlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetwatcher',
            old_name='wordlist',
            new_name='dns_bruteforce_wordlist',
        ),
    ]
