# Generated by Django 5.2.1 on 2025-05-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0017_alter_watchedwildcard_watcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoversubdomain',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='private_watchers.watchedwildcard'),
        ),
    ]
