# Generated by Django 5.2.1 on 2025-05-13 08:29

import private_watchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0018_alter_discoversubdomain_wildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetwatcher',
            name='dns_bruteforce_discoverd',
            field=models.FileField(blank=True, null=True, upload_to=private_watchers.models.user_wordlist_upload_path),
        ),
    ]
