# Generated by Django 5.2.1 on 2025-05-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0019_assetwatcher_dns_bruteforce_discoverd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetwatcher',
            name='dns_bruteforce_discoverd',
        ),
    ]
