# Generated by Django 5.1.3 on 2025-05-13 12:07

import private_watchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0020_remove_assetwatcher_dns_bruteforce_discoverd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwatcher',
            name='dns_bruteforce_wordlist',
            field=models.FileField(blank=True, default=private_watchers.models.default_wordlist_path, null=True, upload_to=private_watchers.models.user_wordlist_upload_path, validators=[private_watchers.models.validate_wordlist_file]),
        ),
    ]
