# Generated by Django 5.2.1 on 2025-05-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0022_alter_tool_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainhttpx',
            name='a_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='cert_issuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='cert_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='cert_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='cert_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='cname',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='content_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='content_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='tls_cipher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='tls_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='technologies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
