# Generated by Django 5.2.1 on 2025-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0023_subdomainhttpx_a_records_subdomainhttpx_cert_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='failed',
            field=models.CharField(default='False'),
        ),
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='has_ssl',
            field=models.CharField(default='False'),
        ),
    ]
