# Generated by Django 5.2.1 on 2025-05-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0024_alter_subdomainhttpx_failed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='cert_issuer',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='cert_subject',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='cert_valid_from',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='cert_valid_to',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='tls_cipher',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='tls_version',
        ),
    ]
