# Generated by Django 5.2.1 on 2025-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0025_remove_subdomainhttpx_cert_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainhttpx',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new'),
        ),
    ]
