# Generated by Django 5.2.1 on 2025-05-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0028_subdomainhttpxchanges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubdomainHttpxChanges',
        ),
    ]
