# Generated by Django 5.2.1 on 2025-05-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0029_delete_subdomainhttpxchanges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='response_time',
        ),
        migrations.CreateModel(
            name='SubdomainHttpxChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('httpx_result_change', models.URLField(blank=True, max_length=150, null=True)),
                ('status_code_change', models.IntegerField(blank=True, null=True)),
                ('title_change', models.CharField(blank=True, max_length=500, null=True)),
                ('server_change', models.CharField(blank=True, max_length=150, null=True)),
                ('technologies_change', models.JSONField(blank=True, default=list)),
                ('has_ssl_change', models.CharField(default='False')),
                ('ip_address_change', models.CharField(blank=True, max_length=120, null=True)),
                ('port_change', models.IntegerField(blank=True, null=True)),
                ('content_type_change', models.CharField(blank=True, max_length=150, null=True)),
                ('content_length_change', models.IntegerField(blank=True, null=True)),
                ('cname_change', models.JSONField(blank=True, default=list)),
                ('a_records_change', models.JSONField(blank=True, default=list)),
                ('failed', models.CharField(default='False')),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new')),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx Changes',
                'verbose_name_plural': 'Subdomain Httpxes Changes',
            },
        ),
    ]
