# Generated by Django 5.2.1 on 2025-05-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0030_remove_subdomainhttpx_response_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpxchanges',
            name='failed',
        ),
    ]
