# Generated by Django 5.2.1 on 2025-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0031_remove_subdomainhttpx_failed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='port',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomainhttpxchanges',
            name='port_change',
            field=models.CharField(blank=True, null=True),
        ),
    ]
