# Generated by Django 5.2.1 on 2025-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0032_alter_subdomainhttpx_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='a_records',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='cname',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='technologies',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomainhttpxchanges',
            name='a_records_change',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subdomainhttpxchanges',
            name='cname_change',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subdomainhttpxchanges',
            name='technologies_change',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
