# Generated by Django 5.1.3 on 2025-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='techniquescategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
