# Generated by Django 5.1.3 on 2025-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0002_alter_techniques_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='techniquescategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
