# Generated by Django 5.1.3 on 2025-05-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='zerodays.zerodaycategory')),
            ],
            options={
                'verbose_name': 'ZeroDay Category',
                'verbose_name_plural': 'ZeroDay Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ZeroDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the zero-day vulnerability.')),
                ('cve_reference', models.CharField(blank=True, help_text='Optional CVE reference if it exists.', max_length=50, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates whether the zero-day has been verified.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zerodays', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerodays.zerodaycategory')),
            ],
            options={
                'verbose_name': 'Zero-Day',
                'verbose_name_plural': 'Zero-Days',
                'ordering': ['-reported_at'],
            },
        ),
    ]
