# Generated by Django 5.1.3 on 2025-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerodays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zeroday',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Zero Day', 'verbose_name_plural': 'Zero Days'},
        ),
        migrations.AddField(
            model_name='zeroday',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zeroday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zeroday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zerodaycategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zerodaycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zerodaycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
