# Generated by Django 5.1.3 on 2025-05-06 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerodays', '0002_alter_zeroday_options_zeroday_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zerodaycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ZeroDayAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('last_bid_time', models.DateTimeField(blank=True, help_text='Last time a bid was placed.', null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeroday_auctions', to=settings.AUTH_USER_MODEL)),
                ('zeroday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='zerodays.zeroday')),
            ],
            options={
                'verbose_name': 'Zero Day Auction',
                'verbose_name_plural': 'Zero Day Auctions',
                'ordering': ['-start_time'],
            },
        ),
    ]
