# Generated by Django 5.1.3 on 2025-05-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerodays', '0004_zeroday_title_alter_zerodayauction_starting_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zerodaybid',
            options={'verbose_name': 'Zero Day Bid', 'verbose_name_plural': 'Zero Day Bids'},
        ),
        migrations.CreateModel(
            name='ZeroDayDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed_at', models.DateField()),
                ('deal_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='zerodays.zerodayauction')),
                ('buyer_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='zerodays.zerodaybid')),
            ],
            options={
                'verbose_name': 'ZeroDay Deal',
                'verbose_name_plural': 'ZeroDay Deals',
                'ordering': ['-completed_at'],
            },
        ),
    ]
