# Generated by Django 5.2.1 on 2025-05-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_watchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedwildcard',
            name='watcher',
        ),
        migrations.RemoveField(
            model_name='discoversubdomain',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='discoversubdomain',
            name='wildcard',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='discovered_subdomain',
        ),
        migrations.RemoveField(
            model_name='jsfilewatcher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jsfilewatchlist',
            name='jsfilewatcher',
        ),
        migrations.RemoveField(
            model_name='watchedjsfile',
            name='jsfilewatchlist',
        ),
        migrations.RemoveField(
            model_name='watchedjsfilechanged',
            name='watchedjsfile',
        ),
        migrations.AlterModelOptions(
            name='discoverdscope',
            options={'verbose_name': 'Discoverd Scope', 'verbose_name_plural': 'Discoverd Scopes'},
        ),
        migrations.DeleteModel(
            name='AssetWatcher',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='WatchedWildcard',
        ),
        migrations.DeleteModel(
            name='DiscoverSubdomain',
        ),
        migrations.DeleteModel(
            name='SubdomainHttpx',
        ),
        migrations.DeleteModel(
            name='JSFileWatcher',
        ),
        migrations.DeleteModel(
            name='JSFileWatchList',
        ),
        migrations.DeleteModel(
            name='WatchedJSFile',
        ),
        migrations.DeleteModel(
            name='WatchedJSFileChanged',
        ),
    ]
