# Generated by Django 5.2.1 on 2025-05-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_watchers', '0002_remove_watchedwildcard_watcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programwatcher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=150),
        ),
    ]
