# Generated by Django 5.2.1 on 2025-05-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_watchers', '0003_alter_programwatcher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverdprogram',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watcher_program', to='public_watchers.programwatcher'),
        ),
    ]
