# Generated by Django 5.2.1 on 2025-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_watchers', '0004_alter_discoverdprogram_watcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoverdprogram',
            options={'ordering': ['-discovered_at'], 'verbose_name': 'Discoverd Program', 'verbose_name_plural': 'Discoverd Programs'},
        ),
        migrations.AlterField(
            model_name='discoverdprogram',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='discoverdprogram',
            unique_together={('watcher', 'name')},
        ),
    ]
