# Generated by Django 5.1.3 on 2025-05-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverdProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('max_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('min_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discovered_at', models.DateTimeField()),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Program Watcher',
                'verbose_name_plural': 'Program Watchers',
            },
        ),
        migrations.CreateModel(
            name='ProgramWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platforms', models.JSONField(default=list)),
                ('last_checked', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('fail', 'Faild'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('notify', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Program Watcher',
                'verbose_name_plural': 'Program Watchers',
            },
        ),
        migrations.CreateModel(
            name='DiscoverdScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('web', 'Web Application'), ('wildcard', 'Wildcard Domain (*.example.com)'), ('mobile', 'Mobile Application (iOS / Android)'), ('api', 'API (REST / GraphQL)'), ('web3', 'Web3 / Smart Contract / dApp'), ('desktop', 'Desktop / Thick Client'), ('iot', 'IoT / Hardware Device'), ('cloud', 'Cloud Infrastructure (AWS, GCP, etc.)'), ('code', 'Source Code / Repository'), ('infrastructure', 'External Infrastructure (IP / DNS / Mail Servers)'), ('physical', 'Physical Security'), ('third_party', 'Third-Party Hosted Apps'), ('others', 'Others')], max_length=150)),
                ('in_scope', models.BooleanField(default=True)),
                ('discovered_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.discoverdprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discoverdprogram',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchers.programwatcher'),
        ),
    ]
