# Generated by Django 5.2.1 on 2025-05-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverdProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('vdp', 'VDP'), ('rdp', 'RDP'), ('others', 'OTHERS')], max_length=100)),
                ('discovered_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available', max_length=100)),
            ],
            options={
                'verbose_name': 'Discoverd Program',
                'verbose_name_plural': 'Discoverd Programs',
            },
        ),
        migrations.CreateModel(
            name='DiscoverSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subdomain', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Discoverd Subdomain',
                'verbose_name_plural': 'Discovered Subdomains',
            },
        ),
        migrations.CreateModel(
            name='ProgramWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_name', models.CharField(max_length=150)),
                ('platform_url', models.URLField()),
                ('check_time', models.IntegerField(default=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='watchers/programwatcher/logo/')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('faild', 'Faild')], default='pending', max_length=150)),
                ('notify', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Program Watcher',
                'verbose_name_plural': 'Program Watchers',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='DiscoverdScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available', max_length=100)),
                ('type', models.CharField(choices=[('ai_model', 'AI Model'), ('web', 'Web Application'), ('wildcard', 'Wildcard Domain (*.example.com)'), ('mobile', 'Mobile Application (iOS / Android)'), ('api', 'API (REST / GraphQL)'), ('web3', 'Web3 / Smart Contract / dApp'), ('desktop', 'Desktop / Thick Client'), ('iot', 'IoT / Hardware Device'), ('cloud', 'Cloud Infrastructure (AWS, GCP, etc.)'), ('code', 'Source Code / Repository'), ('infrastructure', 'External Infrastructure (CIDR / DNS / Mail Servers)'), ('physical', 'Physical Security'), ('third_party', 'Third-Party Hosted Apps'), ('others', 'Others')], max_length=150)),
                ('scope_type', models.CharField(blank=True, choices=[('in_scope', 'In Scope'), ('out_of_scope', 'Out Of Scope')], max_length=100, null=True)),
                ('discovered_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.discoverdprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSFileWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('fail', 'Faild'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('notify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSFileWatcher',
                'verbose_name_plural': 'JSFileWatchers',
            },
        ),
        migrations.CreateModel(
            name='JSFileWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('jsfilewatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.jsfilewatcher')),
            ],
            options={
                'verbose_name': 'JSFileWatchList',
                'verbose_name_plural': 'JSFileWatchLists',
            },
        ),
        migrations.AddField(
            model_name='discoverdprogram',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchers.programwatcher'),
        ),
        migrations.CreateModel(
            name='SubdomainHttpx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status_code', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('server', models.CharField(blank=True, max_length=150, null=True)),
                ('technologies', models.JSONField(default=list)),
                ('has_ssl', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
                ('port', models.IntegerField()),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='watchers.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx',
                'verbose_name_plural': 'Subdomain Httpxes',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='tool',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchers.tool'),
        ),
        migrations.CreateModel(
            name='AssetWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField()),
                ('notify', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('fail', 'Faild'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tools', models.ManyToManyField(related_name='watchers', to='watchers.tool')),
            ],
            options={
                'verbose_name': 'Asset Watcher',
                'verbose_name_plural': 'Asset Watchers',
            },
        ),
        migrations.CreateModel(
            name='WatchedJSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_url', models.URLField(max_length=150)),
                ('current_hash', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked', models.DateTimeField()),
                ('has_changed', models.BooleanField(default=False)),
                ('jsfilewatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.jsfilewatchlist')),
            ],
            options={
                'verbose_name': 'WatchedJSFile',
                'verbose_name_plural': 'WatchedJSFiles',
            },
        ),
        migrations.CreateModel(
            name='WatchedJSFileChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_hash', models.CharField(max_length=150, null=True)),
                ('new_hash', models.CharField(max_length=150, null=True)),
                ('diff_snipped', models.CharField(max_length=150, null=True)),
                ('changed_at', models.DateTimeField()),
                ('watchedjsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.watchedjsfile')),
            ],
            options={
                'verbose_name': 'WatchedJSFileChanged',
                'verbose_name_plural': 'WatchedJSFileChangeds',
            },
        ),
        migrations.CreateModel(
            name='WatchedWildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wildcard', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked', models.DateTimeField()),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.assetwatcher')),
            ],
            options={
                'verbose_name': 'Watched Wildcard',
                'verbose_name_plural': 'Watcher Wildcards',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.watchedwildcard'),
        ),
    ]
