# Generated by Django 5.1.3 on 2025-05-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0002_discoversubdomain_tool_jsfilewatcher_jsfilewatchlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jsfilewatcher',
            options={'verbose_name': 'JSFileWatcher', 'verbose_name_plural': 'JSFileWatchers'},
        ),
        migrations.AlterModelOptions(
            name='jsfilewatchlist',
            options={'verbose_name': 'JSFileWatchList', 'verbose_name_plural': 'JSFileWatchLists'},
        ),
        migrations.AlterModelOptions(
            name='subdomainhttpx',
            options={'verbose_name': 'Subdomain Httpx', 'verbose_name_plural': 'Subdomain Httpxes'},
        ),
        migrations.CreateModel(
            name='WatchedJSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_url', models.URLField(max_length=150)),
                ('current_hash', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked', models.DateTimeField()),
                ('has_changed', models.BooleanField(default=False)),
                ('jsfilewatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.jsfilewatchlist')),
            ],
            options={
                'verbose_name': 'WatchedJSFile',
                'verbose_name_plural': 'WatchedJSFiles',
            },
        ),
        migrations.CreateModel(
            name='WatchedJSFileChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_hash', models.CharField(max_length=150, null=True)),
                ('new_hash', models.CharField(max_length=150, null=True)),
                ('diff_snipped', models.CharField(max_length=150, null=True)),
                ('changed_at', models.DateTimeField()),
                ('watchedjsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchers.watchedjsfile')),
            ],
            options={
                'verbose_name': 'WatchedJSFileChanged',
                'verbose_name_plural': 'WatchedJSFileChangeds',
            },
        ),
    ]
