# Generated by Django 5.1.3 on 2025-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0003_alter_jsfilewatcher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programwatcher',
            name='platforms',
        ),
        migrations.AddField(
            model_name='programwatcher',
            name='check_time',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='programwatcher',
            name='platform_name',
            field=models.CharField(default='bugcrowd', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programwatcher',
            name='platform_url',
            field=models.URLField(default='https://bugcrowd.com'),
            preserve_default=False,
        ),
    ]
