# Generated by Django 5.1.3 on 2025-05-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0004_remove_programwatcher_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programwatcher',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
