# Generated by Django 5.1.3 on 2025-05-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0005_alter_programwatcher_last_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoverdprogram',
            options={'verbose_name': 'Discoverd Program', 'verbose_name_plural': 'Discoverd Programs'},
        ),
    ]
