# Generated by Django 5.1.3 on 2025-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0006_alter_discoverdprogram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programwatcher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='watchers/programwatcher/logo/'),
        ),
    ]
