# Generated by Django 5.1.3 on 2025-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0007_programwatcher_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverdprogram',
            name='max_payout',
        ),
        migrations.RemoveField(
            model_name='discoverdprogram',
            name='min_payout',
        ),
        migrations.AddField(
            model_name='discoverdprogram',
            name='type',
            field=models.CharField(choices=[('vdp', 'VDP'), ('rdp', 'RDP'), ('others', 'OTHERS')], default='vdp', max_length=100),
            preserve_default=False,
        ),
    ]
