# Generated by Django 5.1.3 on 2025-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0008_remove_discoverdprogram_max_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverdprogram',
            name='discovered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
