# Generated by Django 5.1.3 on 2025-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0009_alter_discoverdprogram_discovered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverdprogram',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
