# Generated by Django 5.1.3 on 2025-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0010_alter_discoverdprogram_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverdprogram',
            name='is_new',
        ),
        migrations.AddField(
            model_name='discoverdprogram',
            name='lable',
            field=models.CharField(default='AVAILABLE', max_length=100),
        ),
    ]
