# Generated by Django 5.2.1 on 2025-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0011_remove_discoverdprogram_is_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverdprogram',
            name='lable',
        ),
        migrations.AddField(
            model_name='discoverdprogram',
            name='label',
            field=models.CharField(default='available', max_length=100),
        ),
    ]
