# Generated by Django 5.2.1 on 2025-05-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0012_remove_discoverdprogram_lable_discoverdprogram_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverdprogram',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available', max_length=100),
        ),
    ]
