# Generated by Django 5.2.1 on 2025-05-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereaction',
            name='reacted_at',
        ),
    ]
