# Generated by Django 5.2.1 on 2025-05-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_messagereaction_reacted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereaction',
            name='reacted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
