# Generated by Django 5.2.1 on 2025-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_messagereaction_reacted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='reacted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
