# Generated by Django 5.2.1 on 2025-05-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_messagereaction_reacted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
