# Generated by Django 5.1.3 on 2025-05-06 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniques', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='writeups.writeupcategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WriteUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('vulnerability_type', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preview_text', models.TextField(blank=True, help_text='Teaser for non-buyers')),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeups', to=settings.AUTH_USER_MODEL)),
                ('techniques', models.ManyToManyField(blank=True, null=True, related_name='writeup_techniques', to='techniques.techniques')),
                ('tools_used', models.ManyToManyField(blank=True, null=True, related_name='writeup_tools', to='tools.tool')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeup', to='writeups.writeupcategory')),
            ],
            options={
                'verbose_name': 'WriteUp',
                'verbose_name_plural': 'WriteUps',
            },
        ),
    ]
