# Generated by Django 5.2 on 2025-05-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
