# Generated by Django 5.2 on 2025-05-04 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0003_rename_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeup', to='writeups.category'),
        ),
    ]
