# Generated by Django 5.2 on 2025-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0004_writeup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
