# Generated by Django 5.2 on 2025-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0005_writeup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='techniques',
            field=models.TextField(blank=True, help_text='Comma-separated list of hacking techniques', null=True),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='tools_used',
            field=models.TextField(blank=True, help_text='Comma-separated list of tools', null=True),
        ),
    ]
