# Generated by Django 5.2 on 2025-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0006_alter_writeup_techniques_alter_writeup_tools_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='download_file',
        ),
    ]
