# Generated by Django 5.2 on 2025-05-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0007_remove_writeup_download_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeup',
            options={'verbose_name': 'WriteUp', 'verbose_name_plural': 'WriteUps'},
        ),
    ]
