# Generated by Django 5.1.3 on 2025-05-03 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workplace/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='workplace/banners/')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workplace',
                'verbose_name_plural': 'workplaces',
                'ordering': ['-id'],
            },
        ),
    ]
