# Generated by Django 5.1.3 on 2025-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='github_repo_url',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='preview_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='tools/images/'),
        ),
    ]
