# Generated by Django 5.1.3 on 2025-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_github_repo_url_alter_tool_preview_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
