# Generated by Django 5.1.3 on 2025-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_created_at_alter_toolcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
