# Generated by Django 5.1.3 on 2025-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_tool_created_at_alter_toolcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='demo_video_file',
            field=models.FileField(blank=True, null=True, upload_to='tools/Tool/demo/videos/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='tools/Tool/files/'),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='tool/ToolImage/images/'),
        ),
    ]
